name: wiki page to entries and IME dicts

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml pykakasi

      - name: Create data directory
        run: mkdir -p data

      - name: Run wiki_page_to_entries.py
        run: python scripts/wiki_page_to_entries.py
      
      - name: Create dictionaries directory
        run: mkdir -p dictionaries

      - name: Run entries_to_ime_dicts.py
        run: python scripts/entries_to_ime_dicts.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/seitei_goroku_entries.csv
          git commit -m "Update seitei_goroku_entries.csv [bot]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
